### ISSUE TITLE
Need guidance for modifying vesting contract

### ISSUE THREAD

**Issue by borsemayur2** [0xpetersatoshi/erc20-vesting-contract#1]
I'm trying to create token vesting contract where the admin can distribute the token to given addresses (eg. 5) evenly for 12 months with per minute release schedule. I'm beginner in the domain and need some guidance.

**Comment by 0xpetersatoshi** [comment]
Hi @borsemayur2 , I believe you should be able to accomplish this with the way the `addVestingSchedule` is currently structured. You should just enter 0 for the `cliffSeconds` argument and 31536000 for the `vestingSeconds` argument (12 months). That should create a vesting contract that vests linearly over 12 months. The vesting will however happen on a per second basis, not per minute so you might have to modify the code to accomplish that if that's a hard requirement. Additionally, the method only supports adding one address at a time. If you want to be able to do it for multiple addresses at once then a simple approach would be to create a new method that accepts an array of addresses and loops through the array and creates a new schedule for each address. Hope that helps!

**Comment by borsemayur2** [comment]
Thanks a lot
